/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-06-30 13:39:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Mantenimientos.GestionEmpleado;
import Servlets.ValidarServlet;
import Entidad.Empleado;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.Connection;
import Entidad.Combustible;
import java.awt.event.ItemEvent;
import org.apache.tomcat.util.descriptor.tld.TldRuleSet.Variable;
import org.eclipse.jdt.internal.compiler.ast.ForeachStatement;
import org.apache.jasper.tagplugins.jstl.core.ForEach;
import Entidad.Venta;
import java.util.List;

public final class Ventas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.awt.event.ItemEvent");
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("org.apache.jasper.tagplugins.jstl.core.ForEach");
    _jspx_imports_classes.add("Entidad.Empleado");
    _jspx_imports_classes.add("Mantenimientos.GestionEmpleado");
    _jspx_imports_classes.add("Servlets.ValidarServlet");
    _jspx_imports_classes.add("Entidad.Venta");
    _jspx_imports_classes.add("java.sql.PreparedStatement");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("org.eclipse.jdt.internal.compiler.ast.ForeachStatement");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("Entidad.Combustible");
    _jspx_imports_classes.add("org.apache.tomcat.util.descriptor.tld.TldRuleSet.Variable");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>Ventas</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ\" crossorigin=\"anonymous\">\r\n");
      out.write("    <style>\r\n");
      out.write("    	@media print{\r\n");
      out.write("    		.tarjetaDatos, .btn, .accion{\r\n");
      out.write("    			display: none;\r\n");
      out.write("    		}\r\n");
      out.write("    	} \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");

		Class.forName("com.mysql.jdbc.Driver");
		String url = "jdbc:mysql://localhost:3306/BDCentenario23";
		String usuario = "root";
		String clave = "mysql";
		String sql ;
		Connection cn = DriverManager.getConnection(url,usuario,clave) ;
		PreparedStatement pstm ;
		ResultSet rs ;
	
      out.write("\r\n");
      out.write("	<div class=\"m-4\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-4 tarjetaDatos\">\r\n");
      out.write("				<div class=\"card shadow\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<form action=\"Controlador?menu=Venta\" method=\"post\">\r\n");
      out.write("							<div class=\"form-group row mb-1\">\r\n");
      out.write("								<h6>Datos del Cliente:</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group row mb-1\">\r\n");
      out.write("								<div class=\"col-6 d-flex\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"txtDniCliente\"id=\"codCliente\" placeholder=\"DNI\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cliente.getDniCliente() }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("									<button type=\"submit\" class=\"btn btn-primary\" value=\"BuscarCliente\" name=\"accion\" id=\"buscarCliente\">\r\n");
      out.write("										<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("										  <path d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z\"/>\r\n");
      out.write("										</svg>\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("										<input type=\"text\" class=\"form-control\" name=\"txtCliente\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cliente.getNomCliente()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"nomCliente\" placeholder=\"Nombre del Cliente\">\r\n");
      out.write("									</div>\r\n");
      out.write("								<div class=\" mt-2\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"txtCliente\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cliente.getApeCliente()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"nomCliente\" placeholder=\"Apellido del Cliente\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group row mb-2\">\r\n");
      out.write("								<h6>Datos del Producto:</h6>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<label>Combustible:</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<!-- Button trigger modal -->\r\n");
      out.write("									<button type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">\r\n");
      out.write("									  Lista Combustibles\r\n");
      out.write("									</button>\r\n");
      out.write("									\r\n");
      out.write("									<!-- Modal -->\r\n");
      out.write("									<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("									  <div class=\"modal-dialog\">\r\n");
      out.write("									    <div class=\"modal-content\">\r\n");
      out.write("									      <div class=\"modal-header\">\r\n");
      out.write("									        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Lista de los Combustibles</h1>\r\n");
      out.write("									        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("									      </div>\r\n");
      out.write("									      <div class=\"modal-body\">\r\n");
      out.write("									        <table class=\"table\">\r\n");
      out.write("												<tr>\r\n");
      out.write("													<td>Codigo</td>\r\n");
      out.write("													<td>Producto</td>\r\n");
      out.write("													<td>Capacidad</td>\r\n");
      out.write("													<td>Precio</td>\r\n");
      out.write("													<td>Estado</td>\r\n");
      out.write("												</tr>\r\n");
      out.write("												");

													sql = "select * from productoCombustible";
													pstm = cn.prepareStatement(sql);
													rs = pstm.executeQuery();
													while(rs.next()){
												
      out.write("\r\n");
      out.write("												<tr>\r\n");
      out.write("														<td>");
      out.print( rs.getString(1) );
      out.write("</td>\r\n");
      out.write("														<td>");
      out.print( rs.getString(2) );
      out.write("</td>\r\n");
      out.write("														<td>");
      out.print( rs.getDouble(3) );
      out.write("</td>\r\n");
      out.write("														<td>");
      out.print( rs.getDouble(4) );
      out.write("</td>\r\n");
      out.write("														<td>");
      out.print( rs.getString(5) );
      out.write("</td>\r\n");
      out.write("												</tr>\r\n");
      out.write("												");
} 
      out.write("\r\n");
      out.write("											</table>\r\n");
      out.write("									      </div>\r\n");
      out.write("									      <div class=\"modal-footer\">\r\n");
      out.write("									        <button type=\"button\" class=\"btn btn-danger\" data-bs-dismiss=\"modal\">Cerrar</button>\r\n");
      out.write("									      </div>\r\n");
      out.write("									    </div>\r\n");
      out.write("									  </div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group row\">\r\n");
      out.write("								<div class=\"col-6 d-flex\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"txtCodigo\" placeholder=\"Codigo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${combustible.getCodProdComb() }", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("									<button type=\"submit\" class=\"btn btn-primary\" value=\"BuscarCombustible\" name=\"accion\" id=\"buscarCombustible\">\r\n");
      out.write("										<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("										  <path d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z\"/>\r\n");
      out.write("										</svg>\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"txtCombustible\" placeholder=\"Combustible\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${combustible.getNomComb()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group row mb-2\">\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"txtPrecio\" id=\"precio\" placeholder=\"S/.0.00\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${combustible.getPrecio()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<input type=\"number\" class=\"form-control\" name=\"txtCantidad\" id=\"cantidad\" placeholder=\"Cantidad\" value=\"1\"  title=\"Ingrese un número decimal válido\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<button type=\"submit\" class=\"btn btn-primary\" value=\"AgregarCombustible\" name=\"accion\" id=\"agregar\">\r\n");
      out.write("									<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-bag-plus-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("									  <path fill-rule=\"evenodd\" d=\"M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0zM8.5 8a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V12a.5.5 0 0 0 1 0v-1.5H10a.5.5 0 0 0 0-1H8.5V8z\"/>\r\n");
      out.write("									</svg>\r\n");
      out.write("									 Agregar\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group row mb-2\">\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<label>Tienda:</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<button type=\"button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#listaTienda\">\r\n");
      out.write("									  Lista Tienda\r\n");
      out.write("									</button>\r\n");
      out.write("									<!-- Modal -->\r\n");
      out.write("									<div class=\"modal fade\" id=\"listaTienda\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("									  <div class=\"modal-dialog\">\r\n");
      out.write("									    <div class=\"modal-content\">\r\n");
      out.write("									      <div class=\"modal-header\">\r\n");
      out.write("									        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Lista de los Productos</h1>\r\n");
      out.write("									        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("									      </div>\r\n");
      out.write("									      <div class=\"modal-body\">\r\n");
      out.write("									        <table class=\"table\">\r\n");
      out.write("												<tr>\r\n");
      out.write("													<td>Codigo</td>\r\n");
      out.write("													<td>Producto</td>\r\n");
      out.write("													<td>Precio</td>\r\n");
      out.write("													<td>Stock</td>\r\n");
      out.write("												</tr>\r\n");
      out.write("												");

													sql = "select * from productoTienda";
													pstm = cn.prepareStatement(sql);
													rs = pstm.executeQuery();
													while(rs.next()){
												
      out.write("\r\n");
      out.write("												<tr>\r\n");
      out.write("														<td>");
      out.print( rs.getString(1) );
      out.write("</td>\r\n");
      out.write("														<td>");
      out.print( rs.getString(2) );
      out.write("</td>\r\n");
      out.write("														<td>");
      out.print( rs.getDouble(5) );
      out.write("</td>\r\n");
      out.write("														<td>");
      out.print( rs.getInt(6) );
      out.write("</td>\r\n");
      out.write("												</tr>\r\n");
      out.write("												");
} 
      out.write("\r\n");
      out.write("											</table>\r\n");
      out.write("									      </div>\r\n");
      out.write("									      <div class=\"modal-footer\">\r\n");
      out.write("									        <button type=\"button\" class=\"btn btn-danger\" data-bs-dismiss=\"modal\">Cerrar</button>\r\n");
      out.write("									      </div>\r\n");
      out.write("									    </div>\r\n");
      out.write("									  </div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group row mb-2\">\r\n");
      out.write("								<div class=\"col-6 d-flex\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"txtCodPro\" id=\"codProducto\" placeholder=\"Codigo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.getCodProdTie()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("									<button type=\"submit\" class=\"btn btn-primary\" value=\"BuscarProducto\" name=\"accion\" id=\"buscarProducto\">\r\n");
      out.write("										<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-search\" viewBox=\"0 0 16 16\">\r\n");
      out.write("										  <path d=\"M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z\"/>\r\n");
      out.write("										</svg>\r\n");
      out.write("									</button>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"txtProducto\" id=\"nomProducto\" placeholder=\"Producto\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.getNomProdTie()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group row mb-2\">\r\n");
      out.write("								<div class=\"col-6\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"txtPrecioProducto\" id=\"precio\" placeholder=\"S/.0.00\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.getPrecio()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-3\">\r\n");
      out.write("									<input type=\"number\" class=\"form-control\" name=\"txtCantidadProducto\" id=\"cantidad\" placeholder=\"Cant\" value=\"1\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-3\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" name=\"txtStock\" id=\"stockProducto\" placeholder=\"Stock\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${producto.getStock()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<button type=\"submit\" class=\"btn btn-primary\" value=\"AgregarProducto\" name=\"accion\" id=\"agregar\">\r\n");
      out.write("									<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-bag-plus-fill\" viewBox=\"0 0 16 16\">\r\n");
      out.write("									  <path fill-rule=\"evenodd\" d=\"M10.5 3.5a2.5 2.5 0 0 0-5 0V4h5v-.5zm1 0V4H15v10a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V4h3.5v-.5a3.5 3.5 0 1 1 7 0zM8.5 8a.5.5 0 0 0-1 0v1.5H6a.5.5 0 0 0 0 1h1.5V12a.5.5 0 0 0 1 0v-1.5H10a.5.5 0 0 0 0-1H8.5V8z\"/>\r\n");
      out.write("									</svg>\r\n");
      out.write("									 Agregar\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"col-8\">\r\n");
      out.write("				<div class=\"card shadow\"  style=\"width: 800px\">\r\n");
      out.write("					<div class=\"card-body\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-8\"></div>\r\n");
      out.write("							<div class=\"col-4 d-flex\">\r\n");
      out.write("								<label class=\"m-2\">NumeroSerie</label>\r\n");
      out.write("								<input type=\"text\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nSerie}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<table class=\"table\">\r\n");
      out.write("							<tr class=\"text-center\">\r\n");
      out.write("								<td>Nro</td>\r\n");
      out.write("								<td>Codigo</td>\r\n");
      out.write("								<td>Descripcion</td>\r\n");
      out.write("								<td>Precio</td>\r\n");
      out.write("								<td>Cantidad</td>\r\n");
      out.write("								<td>SubTotal</td>\r\n");
      out.write("								<td class=\"accion\">Acción</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							");

								List<Venta> listaVenta = (List<Venta>) request.getAttribute("ListaVenta"); 
								if(listaVenta != null){
									for(Venta venta:listaVenta){
							
      out.write("\r\n");
      out.write("							<tr class=\"text-center\">\r\n");
      out.write("								<td>");
      out.print( venta.getItem() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( venta.getCodProdTie() != null ? venta.getCodProdTie() : venta.getCodProdComb() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( venta.getDescripcion() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( venta.getPrecio() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( venta.getCantidad() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( venta.getSubTotal() );
      out.write("</td>\r\n");
      out.write("								<td class=\"text-center\">\r\n");
      out.write("									<a href=\"Controlador?menu=Venta&accion=QuitarProducto&item=");
      out.print(venta.getItem() );
      out.write("\" class=\"btn btn-danger\">\r\n");
      out.write("										<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-trash\" viewBox=\"0 0 16 16\">\r\n");
      out.write("										  <path d=\"M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z\"/>\r\n");
      out.write("										  <path d=\"M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z\"/>\r\n");
      out.write("										</svg>\r\n");
      out.write("									</a>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							");
		}
								}
      out.write("\r\n");
      out.write("								\r\n");
      out.write("								");

								List<Venta> listaVentaC = (List<Venta>) request.getAttribute("ListaVentaC"); 
								if(listaVentaC != null){
									for(Venta ventaC:listaVentaC){
							
      out.write("\r\n");
      out.write("							<tr class=\"text-center\">\r\n");
      out.write("								<td>");
      out.print( ventaC.getItem() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( ventaC.getCodProdComb() != null ? ventaC.getCodProdComb() : ventaC.getCodProdTie() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( ventaC.getDescripcion() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( ventaC.getPrecio() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( ventaC.getCantidad() );
      out.write("</td>\r\n");
      out.write("								<td>");
      out.print( ventaC.getSubTotal() );
      out.write("</td>\r\n");
      out.write("								<td class=\"text-center\">\r\n");
      out.write("									<a href=\"Controlador?menu=Venta&accion=QuitarProducto\" class=\"btn btn-danger\">\r\n");
      out.write("										<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" fill=\"currentColor\" class=\"bi bi-trash\" viewBox=\"0 0 16 16\">\r\n");
      out.write("										  <path d=\"M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z\"/>\r\n");
      out.write("										  <path d=\"M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z\"/>\r\n");
      out.write("										</svg>\r\n");
      out.write("									</a>\r\n");
      out.write("								</td>\r\n");
      out.write("							</tr>\r\n");
      out.write("							");
		}
								}
      out.write("							\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card-footer\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-6\">\r\n");
      out.write("								<a href=\"Controlador?menu=Venta&accion=GenerarVenta\" onclick=\"print()\" class=\"btn btn-info\">Generar Venta</a>\r\n");
      out.write("								<a href=\"Controlador?menu=Venta&accion=CancelarVenta\" class=\"btn btn-danger\" >Cancelar</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-6 row\">\r\n");
      out.write("								<div class=\"col-4\"></div>\r\n");
      out.write("								<div class=\"col-4 d-flex\">\r\n");
      out.write("									<label class=\"form-label w-100 mt-1\">Total a Pagar :</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-4\">\r\n");
      out.write("									<input type=\"text\" class=\"form-control\" value=\"S/. ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${TotalPagar}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>	");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
